### ISSUE TITLE
react/PackageList.java:17: error: cannot find symbol

### ISSUE THREAD

**Issue by Shashank2406** [taskrabbit/react-native-zendesk-chat#38]
> Users/shashank/Desktop/ZendeskAndroid/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:17: error: cannot find symbol
> import com.taskrabbit.zendesk.RNZendeskChat.RNZendeskChatPackage;
>                                            ^
>   symbol:   class RNZendeskChatPackage
>   location: package com.taskrabbit.zendesk.RNZendeskChat
> /Users/shashank/Desktop/ZendeskAndroid/android/app/src/main/java/com/zendeskandroid/MainApplication.java:46: error: cannot find symbol
>     ZopimChat.init("YOUR_ZENDESK_ACCOUNT_KEY").build();
>     ^
>   symbol:   variable ZopimChat
>   location: class MainApplication
> /Users/shashank/Desktop/ZendeskAndroid/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:51: error: cannot find symbol
>       new RNZendeskChatPackage()
>           ^
>   symbol:   class RNZendeskChatPackage
>   location: class PackageList
> 3 errors
> 
> FAILURE: Build failed with an exception.

Facing the above issues when running on android. Any Fix for this?
react-native: 0.60.0

**Comment by fbartho** [comment]
React Native 60 has some breaking changes around native modules. All libraries with native android code need to update. You can workaround this by using a tool called “jetifier” but I haven’t tested that with this library yet!

**Comment by Shashank2406** [comment]
@fbartho Do you have a working example for android? For me it is working fine on iOS. Trying on react-native: 0.59.0 now.

**Comment by fbartho** [comment]
The breaking changes in react-native 60 only affect native Android modules. It’s about migrating to AndroidX so that doesn’t affect iOS.

We are using this library in production on React-native 59, and 58, and below!

**Comment by Shashank2406** [comment]
Thanks for the info. It working me now.

**Comment by tommynordli** [comment]
How did you get it to work @Shashank2406?

**Comment by Shashank2406** [comment]
I used jetifier.

**Comment by wktq** [comment]
I still got the same error.
Can I use this repo on Android with RN 0.60 or up now?
or, How can I fix for breaking changes around Android native modules?

**Comment by jackychanfox** [comment]
same issue, I used "npx jetifier" . but same issue.
```error: cannot find symbol class RNZendeskChatPackage```

**Comment by ShaBax** [comment]
any luck ?

**Comment by fbartho** [comment]
Hey friends! For arriving to this ticket in 2020, I'm happy to announce that we're working on full on RN 0.62 support in this milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

We hope to have that shipped in a couple weeks at the latest. And there is a PR with some of that work here: #42 

Please feel free to test that PR and file any changes or fixes you need done. Thanks!
